[program:horizon]
process_name=%(program_name)s
command=php /app/artisan horizon
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
logfile=/var/log/supervisor/horizon.log
logfile_maxbytes=0
stdout_logfile=/var/log/supervisor/horizon.log
stderr_logfile=/var/log/supervisor/horizon.err.log
stdout_logfile_maxbytes = 0
stderr_logfile_maxbytes = 0
stopwaitsecs=3600

[program:worker]
process_name=%(program_name)s
command=php /app/artisan schedule:work
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
logfile=/var/log/supervisor/worker.log
logfile_maxbytes=0
stdout_logfile=/var/log/supervisor/worker.log
stderr_logfile=/var/log/supervisor/worker.err.log
stdout_logfile_maxbytes = 0
stderr_logfile_maxbytes = 0
stopwaitsecs=3600


[program:nginx]
process_name=nginx
command=/usr/sbin/nginx  -g 'daemon off;'
autorestart=true
autostart=true
stopasgroup=true
stderr_logfile=/var/log/supervisor/nginx_error.log
environment=ASPNETCORE_ENVIRONMENT=Production
user=root
stopsignal=INT
startsecs=10
startretries=3